/**
 * Canonical types for the MEV Gladiator Pit.
 * Wire format: all bigint fields are serialized as decimal strings via /serde.
 * Internally (in TS code) we always work with native bigint.
 */

import type { ROUND_MODES, BotColor } from "./constants.js";

/** Hex string with 0x prefix. */
export type Hex = `0x${string}`;

/** Ethereum/Monad address. 0x + 40 hex chars. */
export type Address = Hex;

/** Round mode union derived from constants. */
export type RoundMode = (typeof ROUND_MODES)[number];

export type { BotColor };

/** Kind of victim transaction the synthetic mempool emits. */
export type VictimKind = "swap" | "liquidation" | "arb" | "mint";

/** A prepared, signed transaction visible on the pit's mempool feed. */
export interface ChainTx {
  hash: Hex;
  from: Address;
  to: Address;
  data: Hex;
  value: bigint;
  gasLimit: bigint;
  nonce: number;
  chainId: number;
}

/** A victim tx generated by the coordinator's synthetic mempool. */
export interface VictimTx extends ChainTx {
  /** Monotonic id assigned by the coordinator at emission time. */
  id: number;
  kind: VictimKind;
  /** Theoretical max profit a perfect searcher could extract (wei or token base units). */
  extractableValue: bigint;
  /** Unix ms when emitted to searchers via WS. */
  emittedAt: number;
  /** Unix ms when broadcast on-chain. May be unset until tx_broadcast event fires. */
  broadcastAt?: number;
  /** For swap/arb victims, the pool the swap targets. */
  poolAddress?: Address;
  /** Mode-specific extras, always JSON-safe primitives. */
  metadata?: Record<string, string | number | boolean>;
}

/** Bundle a searcher claims to have submitted, for telemetry only. v1 does not enforce bundles on-chain. */
export interface Bundle {
  searcherId: Address;
  targetVictimId: number;
  txs: ChainTx[];
  submittedAt: number;
}

/** Settled extraction recorded by the coordinator after on-chain confirmation. */
export interface ExtractionEvent {
  searcherId: Address;
  victimId: number;
  amountExtracted: bigint;
  gasSpent: bigint;
  blockNumber: number;
  txHash: Hex;
  /** Unix ms when the coordinator finalized this extraction. */
  timestamp: number;
  trashTalk?: string;
  roundId: number;
}

/** A registered searcher. */
export interface BotHandle {
  id: Address;
  displayName: string;
  walletAddress: Address;
  registeredAt: number;
  color: BotColor;
}

/** Aggregated score for one bot at a point in time. */
export interface Score {
  searcherId: Address;
  displayName: string;
  color: BotColor;
  totalExtracted: bigint;
  kills: number;
  gasSpent: bigint;
  /** totalExtracted - gasSpent; can be negative. */
  netProfit: bigint;
  rank: number;
}

/** Active or scheduled round configuration. */
export interface RoundConfig {
  roundId: number;
  mode: RoundMode;
  durationMs: number;
  victimRateMs: number;
  startedAt: number;
  endsAt: number;
}

/** Final round summary. */
export interface RoundResult {
  roundId: number;
  winner?: BotHandle;
  finalScores: Score[];
  totalExtracted: bigint;
  totalVictims: number;
}

/** A block as the dashboard displays it. */
export interface BlockView {
  blockNumber: number;
  timestamp: number;
  cells: BlockCell[];
}

/** One cell in the dashboard's parallel-execution block visualization. */
export interface BlockCell {
  txHash: Hex;
  kind: "victim" | "extraction-win" | "extraction-fail" | "other";
  actor?: Address;
  value?: bigint;
}
